import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import {Header} from "@/components/shared/Header";
import {Footer} from "@/components/shared/Footer";

const roboto = Roboto({
    weight: ["100", "300", "500", "700"],
    subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "La Camarrillada del Año",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={roboto.className}>
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
